### PR TITLE
Fix #10680 - std.getopt doesn't accept const(string)[] anymore

### LINKED ISSUE #10680: [REG2.111] std.getopt doesn't accept `const(string)[]` anymore
```D
void main() {
    import std.getopt;

    const(string)[] s;
    string[] args;
    getopt(args, "-s", &s);
}
```

This compiles fine with DMD/Phobos v2.110.0, but doesn't compile with v2.111.0-beta.1:
```
/home/mkinkelin/dlang/dmd-2.111.0-beta.1/linux/bin64/../../src/phobos/std/getopt.d(620): Error: cannot modify `const` expression `*receiver`
        *receiver = to!(typeof(*receiver))(value);
        ^
/home/mkinkelin/dlang/dmd-2.111.0-beta.1/linux/bin64/../../src/phobos/std/getopt.d(964): Error: template instance `std.getopt.handleConversion!(const(string))` error instantiating
                    handleConversion(option, val, &tmp, i);
                                    ^
/home/mkinkelin/dlang/dmd-2.111.0-beta.1/linux/bin64/../../src/phobos/std/getopt.d(772):        instantiated from here: `handleOption!(const(string)[]*)`
            bool optWasHandled = handleOption(option, receiver, args, cfg, incremental);
                                             ^
/home/mkinkelin/dlang/dmd-2.111.0-beta.1/linux/bin64/../../src/phobos/std/getopt.d(430):        instantiated from here: `getoptImpl!(string, const(string)[]*)`
    getoptImpl(args, cfg, rslt, excep, visitedLongOpts, visitedShortOpts, opts);
              ^
getopt_bug.d(6):        instantiated from here: `getopt!(string, const(string)[]*)`
    getopt(args, "-s", &s);
          ^
```

Introduced in #10593.

### PR DESCRIPTION
**Pull request by schveiguy**
Reworked the conversion function so it returns the value instead of accepting a (possibly const) pointer.

### CODE REVIEW

**Review by kinke — APPROVED** [review]

**Comment by kinke** [comment]
Thanks Steven for taking care of this! (FWIW, needed to compile reggae...) - I guess the simple GitHub issue ref is enough for the upcoming changelog generator?

**Comment by schveiguy** [comment]
Hm... I don't know the magic thing to say to get the issue to auto-close...

**Comment by jmdavis** [comment]
> Hm... I don't know the magic thing to say to get the issue to auto-close...

I never seem to be able to get it right. The documentation explaining it is here: https://docs.github.com/en/issues/tracking-your-work-with-issues/using-issues/linking-a-pull-request-to-an-issue

Looking at that page and at the title here though, I would have thought that it would have worked.

**Comment by schveiguy** [comment]
Oh! I know. This only happens if you merge to master. OK.
