### ISSUE TITLE
[REG2.111] `toString()`-related regression (related to Nullable and/or Appender)

### ISSUE THREAD

**Issue by kinke** [dlang/phobos#10715]
This fails with DMD v2.111.0-rc.1:
```D
// a.d:
import b;
enum ast = parseDeclarations();

// b.d:
module b;

import std.typecons : Nullable;
import std.array : appender;

struct Type {
    Nullable!(Type[]) templateArgs;
}

Type[] parseDeclarations() {
    auto members = appender!(Type[]);
    return members.data;
}
```

```
$ dmd -o- a.d
/home/mkinkelin/dlang/dmd-2.111.0-sym1/linux/bin64/../../src/phobos/std/format/internal/write.d(2517): Error: expression `hasToString!(const(Nullable!(Type[])), char)` of type `void` does not have a boolean value
if ((is(T == struct) || is(T == union)) && (hasToString!(T, Char) || !is(BuiltinTypeOf!T))
                                            ^
/home/mkinkelin/dlang/dmd-2.111.0-sym1/linux/bin64/../../src/phobos/std/format/write.d(1239): Error: none of the overloads of template `std.format.internal.write.formatValueImpl` are callable using argument types `!()(Appender!string, const(Nullable!(Type[])), const(FormatSpec!char))`
    formatValueImpl(w, val, f);
                   ^
/home/mkinkelin/dlang/dmd-2.111.0-sym1/linux/bin64/../../src/phobos/std/format/internal/write.d(31):        Candidates are: `formatValueImpl(Writer, T, Char)(auto ref Writer w, const(T) obj, ref scope const FormatSpec!Char f)`
  with `Writer = Appender!string,
       T = Nullable!(Type[]),
       Char = char`
  must satisfy the following constraint:
`       is(BooleanTypeOf!T)`
void formatValueImpl(Writer, T, Char)(auto ref Writer w, const(T) obj, scope const ref FormatSpec!Char f)
     ^
/home/mkinkelin/dlang/dmd-2.111.0-sym1/linux/bin64/../../src/phobos/std/format/internal/write.d(105):                        `formatValueImpl(Writer, T, Char)(auto ref Writer w, const(T) obj, ref scope const FormatSpec!Char f)`
  with `Writer = Appender!string,
       T = Nullable!(Type[]),
       Char = char`
  must satisfy the following constraint:
`       is(immutable(T) == immutable(typeof(null)))`
void formatValueImpl(Writer, T, Char)(auto ref Writer w, const(T) obj, scope const ref FormatSpec!Char f)
     ^
/home/mkinkelin/dlang/dmd-2.111.0-sym1/linux/bin64/../../src/phobos/std/format/internal/write.d(139):                        `formatValueImpl(Writer, T, Char)(auto ref Writer w, const(T) obj, ref scope const FormatSpec!Char f)`
  with `Writer = Appender!string,
       T = Nullable!(Type[]),
       Char = char`
  must satisfy the following constraint:
`       is(IntegralTypeOf!T)`
void formatValueImpl(Writer, T, Char)(auto ref Writer w, const(T) obj, scope const ref FormatSpec!Char f)
     ^
/home/mkinkelin/dlang/dmd-2.111.0-sym1/linux/bin64/../../src/phobos/std/format/internal/write.d(569):                        `formatValueImpl(Writer, T, Char)(auto ref Writer w, const(T) obj, ref scope const FormatSpec!Char f)`
  with `Writer = Appender!string,
       T = Nullable!(Type[]),
       Char = char`
  must satisfy the following constraint:
`       is(FloatingPointTypeOf!T)`
void formatValueImpl(Writer, T, Char)(auto ref Writer w, const(T) obj,
     ^
/home/mkinkelin/dlang/dmd-2.111.0-sym1/linux/bin64/../../src/phobos/std/format/internal/write.d(957):                        `formatValueImpl(Writer, T, Char)(auto ref Writer w, const(T) obj, ref scope const FormatSpec!Char f)`
  with `Writer = Appender!string,
       T = Nullable!(Type[]),
       Char = char`
  must satisfy the following constraint:
`       is(immutable(T) : immutable(creal))`
void formatValueImpl(Writer, T, Char)(auto ref Writer w, const(T) obj, scope const ref FormatSpec!Char f)
     ^
/home/mkinkelin/dlang/dmd-2.111.0-sym1/linux/bin64/../../src/phobos/std/format/internal/write.d(977):                        `formatValueImpl(Writer, T, Char)(auto ref Writer w, const(T) obj, ref scope const FormatSpec!Char f)`
  with `Writer = Appender!string,
       T = Nullable!(Type[]),
       Char = char`
  must satisfy the following constraint:
`       is(immutable(T) : immutable(ireal))`
void formatValueImpl(Writer, T, Char)(auto ref Writer w, const(T) obj, scope const ref FormatSpec!Char f)
     ^
/home/mkinkelin/dlang/dmd-2.111.0-sym1/linux/bin64/../../src/phobos/std/format/write.d(1239):        ... (12 more, -v to show) ...
    formatValueImpl(w, val, f);
                   ^
/home/mkinkelin/dlang/dmd-2.111.0-sym1/linux/bin64/../../src/phobos/std/format/internal/write.d(3232): Error: template instance `std.format.write.formatValue!(Appender!string, const(Nullable!(Type[])), char)` error instantiating
    formatValue(w, val, f);
               ^
/home/mkinkelin/dlang/dmd-2.111.0-sym1/linux/bin64/../../src/phobos/std/format/internal/write.d(2570):        instantiated from here: `formatElement!(Appender!string, const(Nullable!(Type[])), char)`
                formatElement(w, val.tupleof[i], f);
                             ^
/home/mkinkelin/dlang/dmd-2.111.0-sym1/linux/bin64/../../src/phobos/std/format/write.d(1239):        instantiated from here: `formatValueImpl!(Appender!string, const(Type), char)`
    formatValueImpl(w, val, f);
                   ^
/home/mkinkelin/dlang/dmd-2.111.0-sym1/linux/bin64/../../src/phobos/std/format/internal/write.d(3232):        instantiated from here: `formatValue!(Appender!string, const(Type), char)`
    formatValue(w, val, f);
               ^
/home/mkinkelin/dlang/dmd-2.111.0-sym1/linux/bin64/../../src/phobos/std/format/internal/write.d(1498):        ... (4 instantiations, -v to show) ...
                formatElement(w, val.front, f);
                             ^
/home/mkinkelin/dlang/dmd-2.111.0-sym1/linux/bin64/../../src/phobos/std/typecons.d(3854):        instantiated from here: `toString!(Appender!string)`
        toString(app, spec);
                ^
b.d(7):        instantiated from here: `Nullable!(Type[])`
    Nullable!(Type[]) templateArgs;
    ^
/home/mkinkelin/dlang/dmd-2.111.0-sym1/linux/bin64/../../src/phobos/std/format/internal/write.d(2517): Error: template instance `std.format.internal.write.hasToString!(const(Nullable!(Type[])), char)` error instantiating
if ((is(T == struct) || is(T == union)) && (hasToString!(T, Char) || !is(BuiltinTypeOf!T))
                                            ^
/home/mkinkelin/dlang/dmd-2.111.0-sym1/linux/bin64/../../src/phobos/std/format/write.d(1239): Error: none of the overloads of template `std.format.internal.write.formatValueImpl` are callable using argument types `!()(InPlaceAppender!string, const(Nullable!(Type[])), const(FormatSpec!char))`
    formatValueImpl(w, val, f);
                   ^
/home/mkinkelin/dlang/dmd-2.111.0-sym1/linux/bin64/../../src/phobos/std/format/internal/write.d(31):        Candidates are: `formatValueImpl(Writer, T, Char)(auto ref Writer w, const(T) obj, ref scope const FormatSpec!Char f)`
void formatValueImpl(Writer, T, Char)(auto ref Writer w, const(T) obj, scope const ref FormatSpec!Char f)
     ^
/home/mkinkelin/dlang/dmd-2.111.0-sym1/linux/bin64/../../src/phobos/std/format/internal/write.d(105):                        `formatValueImpl(Writer, T, Char)(auto ref Writer w, const(T) obj, ref scope const FormatSpec!Char f)`
void formatValueImpl(Writer, T, Char)(auto ref Writer w, const(T) obj, scope const ref FormatSpec!Char f)
     ^
/home/mkinkelin/dlang/dmd-2.111.0-sym1/linux/bin64/../../src/phobos/std/format/internal/write.d(139):                        `formatValueImpl(Writer, T, Char)(auto ref Writer w, const(T) obj, ref scope const FormatSpec!Char f)`
void formatValueImpl(Writer, T, Char)(auto ref Writer w, const(T) obj, scope const ref FormatSpec!Char f)
     ^
/home/mkinkelin/dlang/dmd-2.111.0-sym1/linux/bin64/../../src/phobos/std/format/internal/write.d(569):                        `formatValueImpl(Writer, T, Char)(auto ref Writer w, const(T) obj, ref scope const FormatSpec!Char f)`
void formatValueImpl(Writer, T, Char)(auto ref Writer w, const(T) obj,
     ^
/home/mkinkelin/dlang/dmd-2.111.0-sym1/linux/bin64/../../src/phobos/std/format/internal/write.d(957):                        `formatValueImpl(Writer, T, Char)(auto ref Writer w, const(T) obj, ref scope const FormatSpec!Char f)`
void formatValueImpl(Writer, T, Char)(auto ref Writer w, const(T) obj, scope const ref FormatSpec!Char f)
     ^
/home/mkinkelin/dlang/dmd-2.111.0-sym1/linux/bin64/../../src/phobos/std/format/internal/write.d(977):                        `formatValueImpl(Writer, T, Char)(auto ref Writer w, const(T) obj, ref scope const FormatSpec!Char f)`
void formatValueImpl(Writer, T, Char)(auto ref Writer w, const(T) obj, scope const ref FormatSpec!Char f)
     ^
/home/mkinkelin/dlang/dmd-2.111.0-sym1/linux/bin64/../../src/phobos/std/format/write.d(1239):        ... (12 more, -v to show) ...
    formatValueImpl(w, val, f);
                   ^
/home/mkinkelin/dlang/dmd-2.111.0-sym1/linux/bin64/../../src/phobos/std/format/internal/write.d(3232): Error: template instance `std.format.write.formatValue!(InPlaceAppender!string, const(Nullable!(Type[])), char)` error instantiating
    formatValue(w, val, f);
               ^
/home/mkinkelin/dlang/dmd-2.111.0-sym1/linux/bin64/../../src/phobos/std/format/internal/write.d(2570):        instantiated from here: `formatElement!(InPlaceAppender!string, const(Nullable!(Type[])), char)`
                formatElement(w, val.tupleof[i], f);
                             ^
/home/mkinkelin/dlang/dmd-2.111.0-sym1/linux/bin64/../../src/phobos/std/format/write.d(1239):        instantiated from here: `formatValueImpl!(InPlaceAppender!string, const(Type), char)`
    formatValueImpl(w, val, f);
                   ^
/home/mkinkelin/dlang/dmd-2.111.0-sym1/linux/bin64/../../src/phobos/std/format/internal/write.d(3232):        instantiated from here: `formatValue!(InPlaceAppender!string, const(Type), char)`
    formatValue(w, val, f);
               ^
/home/mkinkelin/dlang/dmd-2.111.0-sym1/linux/bin64/../../src/phobos/std/format/internal/write.d(1498):        ... (6 instantiations, -v to show) ...
                formatElement(w, val.front, f);
                             ^
/home/mkinkelin/dlang/dmd-2.111.0-sym1/linux/bin64/../../src/phobos/std/array.d(4494):        instantiated from here: `Appender!(Type[])`
Appender!A appender(A)()
^
b.d(11):        instantiated from here: `appender!(Type[])`
    auto members = appender!(Type[]);
```

It works fine with DMD v2.110.0, and also when using the v2.110.0 druntime/Phobos imports.

**Comment by kinke** [comment]
Seems like `std.array` is the problem - when replacing the v2.111 module with the v2.110 one, the testcase works.

**Comment by kinke** [comment]
This most likely just made a compiler bug appear; I'm currently trying to dustmite the whole thing.

**Comment by kinke** [comment]
Filed as compiler bug instead: https://github.com/dlang/dmd/issues/21098
