### PR TITLE
Revert "Fix Issue 9489 - writeln of struct with disabled copy ctor"

### PR DESCRIPTION
**Pull request by ibuclaw**
Reverts dlang/phobos#8055

### CODE REVIEW

**Review by thewilsonator — APPROVED** [review]

**Comment by ibuclaw** [comment]
@Geod24 @thewilsonator mind if I also commit a unittest for 21920?

**Comment by Geod24** [comment]
Of course not :)

**Comment by ibuclaw** [comment]
Done!

**Comment by RazvanN7** [comment]
Doesn't this also fix 21920?

**Review by RazvanN7 — APPROVED** [review]

**Comment by ibuclaw** [comment]
@RazvanN7 added "fix" to the commit message.

**Comment by CyberShadow** [comment]
Shouldn't this target `stable`?

**Comment by Geod24** [comment]
No, the offending commit is not in stable.

**Comment by RazvanN7** [comment]
> No, the offending commit is not in stable.

Wow, it's like you read my mind. I did think of suggesting to target stable, but then realized that the offending commit got merged last week. 10 seconds later I see "No, the offending commit is not in stable"

**Comment by ibuclaw** [comment]
The issue says `REG master` not `REG stable`. ;-)

**Comment by CyberShadow** [comment]
Of course, sorry for the noise :)

**Comment by ibuclaw** [comment]
Who broke the test-suite?
```
generated/linux/release/64/benchmark.o:benchmark/runbench.d:function _D8runbench8runTestsFSQu6ConfigZv:
error: undefined reference to '_D3std4path12absolutePathFNaNfAyaLQeZQh'
--
generated/linux/release/64/benchmark.o:benchmark/runbench.d:function _D8runbench8runTestsFSQu6ConfigZv:
error: undefined reference to  '_D3std4path12absolutePathFNaNfAyaLQeZQh'
```
