### PR TITLE
[std.container.rbtree] Fix rbtree correct so it works with DIP1000 an…

### PR DESCRIPTION
**Pull request by cbleser**
Fix rbtree correctly so it works with DIP1000 and dmd-2.101 or higher

The RebBlackTree._add parameter has a scope attribute it can't have a scope if it references to the element allocated. 
The PR corrects this by removing the scope.

Example. 
Which can't compile with -dip1000 -dip25 

file rbtree_scope.d
```
import std.container.rbtree;

@safe:
enum Type
{
    REMOVE = -1,
    NONE = 0,
    ADD = 1
}

class Archive
{
    string fingerprint;
    Type type;
    this(string f, Type t)
    {
        fingerprint = f;
        type = t;
    }
}

alias Archives = RedBlackTree!(Archive, (a,
        b) @safe => (a.fingerprint < b.fingerprint)
        || (a.fingerprint == b.fingerprint) && (a.type < a.type));

@safe
unittest
{
    auto rbt = new Archives;
    rbt.insert(new Archive("test", Type.ADD));
}

```

```
dmd rbtest_scope.d -unittest -main
rbtest_scope.d(30): Deprecation: `@safe` function `__unittest_L27_C1` calling `stableInsert`
/usr/include/dmd/phobos/std/container/rbtree.d(1273):        which calls `std.container.rbtree.RedBlackTree!(Archive, (a, b) @safe => a.fingerprint < b.fingerprint || a.fingerprint == b.fingerprint && (a.type < a.type), false).RedBlackTree._add`
/usr/include/dmd/phobos/std/container/rbtree.d(898):        which would be `@system` because of:
/usr/include/dmd/phobos/std/container/rbtree.d(898):        scope variable `n` assigned to non-scope parameter `v` calling `allocate`
```

And
```
dmd -dip1000 -dip25 rbtest_scope.d -unittest -main
rbtest_scope.d(30): Error: `@safe` function `rbtest_scope.__unittest_L27_C1` cannot call `@system` function `std.container.rbtree.RedBlackTree!(Archive, (a, b) @safe => a.fingerprint < b.fingerprint || a.fingerprint == b.fingerprint && (a.type < a.type), false).RedBlackTree.stableInsert!(Archive).stableInsert`
/usr/include/dmd/phobos/std/container/rbtree.d(890):        which calls `std.container.rbtree.RedBlackTree!(Archive, (a, b) @safe => a.fingerprint < b.fingerprint || a.fingerprint == b.fingerprint && (a.type < a.type), false).RedBlackTree._add`
/usr/include/dmd/phobos/std/container/rbtree.d(898):        which was inferred `@system` because of:
/usr/include/dmd/phobos/std/container/rbtree.d(898):        scope variable `n` assigned to non-scope parameter `v` calling `allocate`
/usr/include/dmd/phobos/std/container/rbtree.d(1264):        `std.container.rbtree.RedBlackTree!(Archive, (a, b) @safe => a.fingerprint < b.fingerprint || a.fingerprint == b.fingerprint && (a.type < a.type), false).RedBlackTree.stableInsert!(Archive).stableInsert` is declared here
```

### CODE REVIEW

**Comment by RazvanN7** [comment]
Have you tried doing it the other way around? I mean, making allocate receive a return scope parameter?

cc @dkorpel , our dip1000 expert.

File: std/container/rbtree.d [hunk 1]
```diff
@@ -2117,7 +2117,7 @@ if ( is(typeof(binaryFun!less((ElementType!Stuff).init, (ElementType!Stuff).init
     auto rbt3 = redBlackTree(chain([0, 1], [7, 5]));
     assert(equal(rbt3[], [0, 1, 5, 7]));
 
-    auto rbt4 = redBlackTree(chain(["hello"], ["world"]));
+    auto rbt4 = redBlackTree(chain(["hello"].idup, ["world"].idup));
```
Comment (dkorpel) [inline std/container/rbtree.d:2120]: An array literal is already GC allocated, why `idup`?

**Review by dkorpel — COMMENTED** [review]
I'm okay with removing `scope` annotations from rbtree, since:
- `RedBlackTree` is a linked data structure, which doesn't work well with DIP1000 which only accounts for a single indirection. I don't think it's safe at all to store stack allocated values in it currently.
- I feel like the attributes were added prematurely. I had to make fixes to the annotations before, as holes in the DIP1000 implementation were plugged.
- Being a templated type, the attributes should be inferred if they can be

**Comment by RazvanN7** [comment]
@cbleser The array literal is not stack allocated. I guess this could be filed as an enhancement report but up until then, drop the idup and let's get this in.

**Comment by RazvanN7** [comment]
ping @cbleser

**Comment by RazvanN7** [comment]
Added the `72h no response->close` label.

File: std/container/rbtree.d (hunk 1 above)
Comment (dkorpel) [reply std/container/rbtree.d:2120]:
```suggestion
    auto rbt4 = redBlackTree(chain(["hello"], ["world"]));
```

Comment (dkorpel) [inline std/container/rbtree.d:2120]:
```suggestion
    auto rbt4 = redBlackTree(chain(["hello"], ["world"]));
```
