### PR TITLE
Merge remote-tracking branch 'upstream/stable' into merge_stable

### PR DESCRIPTION
**Pull request by wilzbach**
Conflicts:
 - std.range.package (in `master` `save` is now annotated with `return scope`)

### CODE REVIEW

**Comment by ZombineDev** [comment]
`vibe.d + vibe-core` fails to link on BuildKite:
```

Linking...
--
  | mongodb/.dub/build/vibe-d-mongodb-test-library-unittest-linux.posix-x86_64-dmd_2085-36D85DDF181792A215C97F8B95F2BD77/vibe-d-mongodb-test-library.o:../.dub/packages/vibe-core-1.6.3-alpha.1/vibe-core/source/vibe/appmain.d:_D39TypeInfo_S3std8typecons__T5TupleTiTdZQl6__initZ: error: undefined reference to '_D3std8typecons__T5TupleTiTdZQl6__initZ'
  | mongodb/.dub/build/vibe-d-mongodb-test-library-unittest-linux.posix-x86_64-dmd_2085-36D85DDF181792A215C97F8B95F2BD77/vibe-d-mongodb-test-library.o:../.dub/packages/vibe-core-1.6.3-alpha.1/vibe-core/source/vibe/appmain.d:function _D3std8typecons__T5TupleTiTdZQl11__xopEqualsFKxSQBuQBt__TQBnTiTdZQBvKxQxZb: error: undefined reference to '_D3std8typecons__T5TupleTiTdZQl__T8opEqualsTxSQBsQBr__TQBlTiTdZQBtZQBhMxFNaNbNiNfxQBlZb'
  | mongodb/.dub/build/vibe-d-mongodb-test-library-unittest-linux.posix-x86_64-dmd_2085-36D85DDF181792A215C97F8B95F2BD77/vibe-d-mongodb-test-library.o:../.dub/packages/vibe-core-1.6.3-alpha.1/vibe-core/source/vibe/appmain.d:function _D3std8typecons__T5TupleTiTdZQl8__xopCmpFKxSQBqQBp__TQBjTiTdZQBrKxQxZi: error: undefined reference to '_D3std8typecons__T5TupleTiTdZQl__T5opCmpTxSQBpQBo__TQBiTiTdZQBqZQBeMxFNaNbNiNfxQBlZi'
  | collect2: error: ld returned 1 exit status
  | Error: linker exited with status 1
  | dmd failed with exit code 1.
```

Perhaps you can try splitting this PR to narrow down / bisect the cause?

**Comment by wilzbach** [comment]
For reference, it started to fail with #6939:

https://buildkite.com/dlang/phobos/builds?branch=stable

**Comment by wilzbach** [comment]
> Perhaps you can try splitting this PR to narrow down / bisect the cause?

I tried with: https://github.com/dlang/phobos/pull/6957

**Comment by aG0aep6G** [comment]
> For reference, it started to fail with #6939

An attempt at a workaround: #6958

**Comment by wilzbach** [comment]
Update the PR to include the workaround from https://github.com/dlang/phobos/pull/6958.

Thanks again @aG0aep6G!
