### PR TITLE
std.process touchups

### PR DESCRIPTION
**Pull request by CyberShadow**
Follow-up to #7726.

This is on stable because it's based on #7726, which targeted stable.

Edit: I will open a separate PR for the changes unrelated to #7726, to avoid putting a lot of stuff in stable.

Edit 2: That didn't work.

### CODE REVIEW

**Comment by CyberShadow** [comment]
I am not comfortable about putting all of this on stable.

Maybe we should revert #7726 on stable and put it back on master.

**Review by thewilsonator — APPROVED** [review]

File: std/process.d [hunk 1]
```diff
@@ -1434,28 +1429,39 @@ version (Windows) @system unittest
...
-    if (pathz == null)  return null;
+    string result;
 
-    foreach (dir; splitter(to!string(pathz), ':'))
-    {
-        auto execPath = buildPath(dir, executable);
-        if (isExecutable(execPath))  return execPath;
-    }
+    environment.getImpl("PATH",
+        (scope const(char)[] path)
```
Comment (MartinNowak) [inline std/process.d:1441]: The callback here is not `@safe` and apparently fails to compile with ldc-1.24.0 on Linux-32.
```
cannot pass argument `__lambda2` of type `void delegate(scope const(char)[] path) @system` to parameter `scope void delegate(const(char)[]) @safe sink`
```

Comment (MartinNowak) [reply std/process.d:1441]: After making it `@safe`
`std/process.d(1448): Error: scope variable dir assigned to execPath with longer lifetime`

Comment (CyberShadow) [reply std/process.d:1441]: If I add `@safe` explicitly, it compiles for me.

How can I reproduce this error?

What error do you get if you add an explicit `@safe` annotation?

Comment (CyberShadow) [reply std/process.d:1441]: > How can I reproduce this error?

Reproduced with `digger run master -- dmd -o- -preview=dip1000 process.d`

Comment (CyberShadow) [reply std/process.d:1441]: Looks like something changed in `dip1000` on master. Not yet sure if this is a regression. Bisecting.

Comment (CyberShadow) [reply std/process.d:1441]: BTW, feel free to revert this if it's blocking anything.

Comment (CyberShadow) [reply std/process.d:1441]: Wow, it was actually caused by a regression in Phobos.

Introduced in #7719.

I suggest reverting that pull request, since it was intended as a regression.

Comment (CyberShadow) [reply std/process.d:1441]: https://github.com/dlang/phobos/pull/7730

Comment (MartinNowak) [reply std/process.d:1441]: See https://github.com/dlang/phobos/pull/7731 @CyberShadow

Comment (CyberShadow) [reply std/process.d:1441]: I think we should prefer #7730 as that addresses a regression visible from outside Phobos.
